name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Client
        working-directory: ./client
        run: npm run build

      - name: Upload Client Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build-artifact
          path: client/dist/
          if-no-files-found: error
          retention-days: 1

  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci

  unit-tests-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci
        
      - name: Run Client Tests
        working-directory: ./client
        run: npm run test

  unit-tests-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci
        
      - name: Run Server Tests
        working-directory: ./server
        run: npm run test
